config/routes.rb
Rails.application.routes.draw do

  resources :templates do
    resources :processed_images, only: [:create, :update]
    get :jcrop, on: :member
  end

  resource :placeholders, only: [:show]
end

app/models/embed_rule.rb
class EmbedRule < ActiveRecord::Base

  DEFAULT_ATTRIBUTES = {
    destination_points: %w(0 0 10 10 150 0 140 10 150 150 140 140 0 150 10 140),
    composite_position_x: 100,
    composite_position_y: 100,
    destination_size_x: 150,
    destination_size_y: 150
  } 

  belongs_to :image_template
  serialize :destination_points

  def destination_points
    (read_attribute(:destination_points) || []).map(&:to_i)
  end

  [:destination_size_x, :destination_size_y, :composite_position_x, :composite_position_y].each do |method_name|
    define_method method_name do
      read_attribute(method_name).to_i
    end
  end
end

app/models/image_template.rb
class ImageTemplate < ActiveRecord::Base
  mount_uploader :image, ImageTemplateUploader

  validates :image, presence: true

  has_many :processed_images, foreign_key: :template_id
  has_many :embed_rules, dependent: :destroy

  accepts_nested_attributes_for :embed_rules, allow_destroy: true

  after_create :add_embed_rule

  private

  def add_embed_rule
    embed_rules.create(EmbedRule::DEFAULT_ATTRIBUTES)
  end
end

app/models/processed_image.rb
class ProcessedImage < ActiveRecord::Base
  belongs_to :template, class_name: ImageTemplate
  belongs_to :embed_rule

  mount_uploader :image, ProcessedImageUploader
  validates :template_id, :image, presence: true

  attr_accessor :prev_image_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/placeholders_controller.rb
class PlaceholdersController < ApplicationController

  def show
    @width  = params[:width]
    @height = params[:height]
  end

end

app/controllers/processed_images_controller.rb
class ProcessedImagesController < ApplicationController
  protect_from_forgery except: :create 

  def create
    @template = ImageTemplate.find(params[:template_id])
    @processed_image = @template.processed_images.build(prev_image_id: params[:processed_image_id])
    @processed_image.embed_rule = @template.embed_rules.find(params[:rule_id])
    @processed_image.assign_attributes( image: params[:file] )

    if @processed_image.save
      render json: @processed_image.to_json
    else
      render json: { errors: @processed_image.errors.full_messages.join(' ') }, status: :unprocessable_entity
    end
  end

  def update
    @template = ImageTemplate.find(params[:template_id])
    @processed_image = @template.processed_images.find(params[:id])
    @processed_image.embed_rule = @template.embed_rules.find(params[:rule_id])
    @processed_image.assign_attributes( image: params[:file] )
    if @processed_image.save
      render json: @processed_image.to_json
    else
      render json: { errors: @processed_image.errors.full_messages.join(' ') }, status: :unprocessable_entity
    end
  end

  private

  def create_params
    params.require(:processed_image).permit(:image)
  end

end

app/controllers/templates_controller.rb
class TemplatesController < ApplicationController

  def new
    @template = ImageTemplate.new
  end

  def jcrop
    @template = ImageTemplate.find(params[:id])
  end

  def create
    @template = ImageTemplate.new(create_params)
    if @template.save
      redirect_to edit_template_path(@template)
    else
      render :new
    end
  end

  def edit
    @template = ImageTemplate.find params[:id]
    render 'edit_step3' and return if params[:step] == "3"
    render 'edit_step2'
  end

  def update
    @template = ImageTemplate.find(params[:id])
    @template.assign_attributes(update_params)
    @template.image.recreate_versions!
    if @template.save
      if params[:commit] == "move-to-step-3"
        redirect_to edit_template_path(@template, step: '3'), notice: "Saved"
      elsif params[:commit] == "template-complete"
        redirect_to template_path(@template)
      else
        redirect_to edit_template_path(@template), notice: "Saved"
      end
    else
      render :edit
    end
  end

  def show
    @template = ImageTemplate.find(params[:id])
  end

  def index
    @templates = ImageTemplate.all
    @col1_items = []
    @col2_items = []
    @col3_items = []
    @templates.each_with_index do |tpl, i|
      @col1_items << tpl if i % 3 == 0
      @col2_items << tpl if i % 3 == 1
      @col3_items << tpl if i % 3 == 2
    end
  end

  private

  def create_params
    params.require(:image_template).permit(:image)
  end

  def update_params
    params.require(:image_template).permit!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/templates_helper.rb
module TemplatesHelper
end

app/views/layouts/_navbar.haml
%nav.navbar.navbar-default
  .container-fluid
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{href: templates_path}= image_tag 'prefolio-logo.png'

    / Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li{ class: ("active" if current_page?(new_template_path)) }= link_to "Add Template", :new_template

app/views/layouts/application.html.haml
!!!
%html{ 'ng-app' => 'prefolioApp' }
  %head
    %title Prefolio
    = stylesheet_link_tag '//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css'
    = stylesheet_link_tag 'application', media: 'all'

    =# javascript_include_tag '//ajax.aspnetcdn.com/ajax/jQuery/jquery-1.9.1.min.js'
    =# javascript_include_tag '//ajax.googleapis.com/ajax/libs/angularjs/1.2.16/angular.min.js'
    =# javascript_include_tag '/assets/angular.min.js'
    = javascript_include_tag 'application'
    = javascript_include_tag '/javascripts/angular-file-upload-shim.min.js'
    = javascript_include_tag '/javascripts/angular-file-upload.min.js'

    = csrf_meta_tags

  %body
    .container

      = render 'layouts/navbar'
      = yield

app/views/placeholders/show.html.haml
:css
  html{ height: 100%; }
  body{
    height: 100%;
    background: #a90329; /* Old browsers */
    background: -moz-linear-gradient(top, #a90329 0%, #8f0222 44%, #6d0019 100%); /* FF3.6+ */
    background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#a90329), color-stop(44%,#8f0222), color-stop(100%,#6d0019)); /* Chrome,Safari4+ */
    background: -webkit-linear-gradient(top, #a90329 0%,#8f0222 44%,#6d0019 100%); /* Chrome10+,Safari5.1+ */
    background: -o-linear-gradient(top, #a90329 0%,#8f0222 44%,#6d0019 100%); /* Opera 11.10+ */
    background: -ms-linear-gradient(top, #a90329 0%,#8f0222 44%,#6d0019 100%); /* IE10+ */
    background: linear-gradient(to bottom, #a90329 0%,#8f0222 44%,#6d0019 100%); /* W3C */
    filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#a90329', endColorstr='#6d0019',GradientType=0 ); /* IE6-9 */
  }
  .text-center{ color: #fff; font-size: 150%; }
  h1{ font-size: 62px; font-weight: bold; }
  h3 span { font-weight: bold; }

.text-center
  %h1 Place image here.
  %h3 
    Best fit 
    %span= @width
    x
    %span= @height
    px

app/views/templates/_progress_bar.haml
.row.form-group
  .col-xs-12
    %ul.nav.nav-pills.nav-justified.thumbnail.setup-panel
      %li{ class: step == 1 ? "active" : "disabled" }
        %a
          %h4.list-group-item-heading Upload template image
          %p.list-group-item-text Step 1
      %li{ class: step == 2 ? "active" : "disabled" }
        %a
          %h4.list-group-item-heading Specify embed area
          %p.list-group-item-text Step 2
      %li{ class: step == 3 ? "active" : "disabled" }
        %a
          %h4.list-group-item-heading Set title & keywords
          %p.list-group-item-text Step 3

app/views/templates/_template.html.haml
.template
  .img-wrapper
    = image_tag tpl.image_url(:small)
    .bg-img-template
      = link_to "Choose", template_path(tpl), class: 'btn btn-large'

app/views/templates/edit.html.haml
= render 'progress_bar', step: 2


#edit-template-form.form-wrapper.marg-bottom{ 'ng-controller' => 'EditTemplateFormCtrl', 'ng-init'=> "init(#{ @template.to_json(include: :embed_rules) })" }
  = simple_form_for @template, url: template_path(@template), html: { class: 'form-horizontal', name: 'TemplateForm' } do |f|
    #template-editor-window
      .image-wrapper{ 'ng-style' => "{ width: template.original_width + 200, height: template.original_height + 200 }" }
        .img-cover
        %canvas#img_canvas{ 'ng-style'=>"{'margin-left': current_rule.composite_position_x, 'margin-top': current_rule.composite_position_y}", height: "{{ current_rule.destination_size_y }}", width: "{{ current_rule.destination_size_x }}" }
        = image_tag @template.image_url

    .row.marg-bottom
      .col-md-12
        Original image size #{ @template.original_width }x#{ @template.original_height }

    .panel.panel-default.embed-rule{ 'ng-repeat' => 'rule in template.embed_rules', 'ng-class' => '{"panel-primary": current_rule == rule  }' }
      .panel-body
        %input{ type: :hidden, name: "template[embed_rules_attributes][][_destroy]", 'ng-model'=>"rule.deleted", value: "{{ rule.deleted }}" }
        .control-buttons.row-fluid

          .col-md-12
            %button.btn.btn-danger.btn-xs.pull-right{ 'ng-hide' => 'rule.deleted', 'eat-click' => true, 'ng-click' => 'remove_rule(rule)' } &times;
            %button.btn.btn-primary.btn-xs{ 'ng-hide' => 'rule.deleted || current_rule == rule', 'eat-click' => true, 'ng-click' => 'select_rule(rule)' } Select

        .alert.alert-danger{ 'ng-show'=>"rule.deleted" }
          Embed rule will be deleted (
          %a{ href: "#", 'ng-click'=>"rule.deleted=undefined", 'eat-click'=> true } Restore
          )

        .row{ 'ng-hide' => 'rule.deleted' }
          %input{ type: :hidden, name: 'image_template[embed_rules_attributes][][id]', value: '{{ rule.id }}' }
          .col-md-7
            .row.marg-bottom
              .col-md-3{ 'ng-repeat'=>'i in [0, 1, 2, 3]' }
                .point
                  .row
                    .col-md-12.text-center {{ point_names[i] }}
                  .row
                    %input.col-md-6{ value: "{{ get_init_distortion_points(rule, i*2) }}", readonly: true, disabled: true, type: :number,  placeholder: 'X' }
                    %input.col-md-6{ value: "{{ get_init_distortion_points(rule, i*2+1) }}", readonly: true, disabled: true, type: :number, placeholder: 'Y' }
                    
                    %input{ value: "{{ get_init_distortion_points(rule, i*2) }}", type: :hidden, name: "image_template[embed_rules_attributes][][destination_points][]" }
                    %input{ value: "{{ get_init_distortion_points(rule, i*2+1) }}", type: :hidden, name: "image_template[embed_rules_attributes][][destination_points][]" }
                  .row
                    %input.col-md-6{ 'ng-change'=>'redraw_canvas()', 'ng-model'=>'rule.destination_points[i*4+2]', value: '{{ rule.destination_points[i*4+2] }}', type: :number, name: "image_template[embed_rules_attributes][][destination_points][]", placeholder: 'X' }
                    %input.col-md-6{ 'ng-change'=>'redraw_canvas()', 'ng-model'=>'rule.destination_points[i*4+3]', value: '{{ rule.destination_points[i*4+3] }}', type: :number, name: "image_template[embed_rules_attributes][][destination_points][]", placeholder: 'Y' }
          .col-md-5
            .row.marg-bottom
              .col-md-6
                .row
                  .col-md-12 Composite position
                .row
                  .col-md-6
                    %label
                      X
                      %input.col-md-12{ name: 'image_template[embed_rules_attributes][][composite_position_x]', 'ng-change'=>'redraw_canvas()', 'ng-model'=>"rule.composite_position_x", type: :number }

                  
                  .col-md-6
                    %label
                      Y
                      %input.col-md-12{ name: 'image_template[embed_rules_attributes][][composite_position_y]', 'ng-change'=>'redraw_canvas()', 'ng-model'=>"rule.composite_position_y", type: :number }

              .col-md-6
                .row
                  .col-md-12 Destination size
                .row
                  .col-md-6
                    %label
                      Width
                      %input.col-md-12{ name: 'image_template[embed_rules_attributes][][destination_size_x]', 'ng-change'=>'redraw_canvas()', 'ng-model'=>"rule.destination_size_x", type: :number }
                 
                  .col-md-6
                    %label
                      Height
                      %input.col-md-12{ name: 'image_template[embed_rules_attributes][][destination_size_y]', 'ng-change'=>'redraw_canvas()', 'ng-model'=>"rule.destination_size_y", type: :number }
    
    %button.btn.btn-primary{ 'eat-click' => true, 'ng-click' => 'add_embed_rule()' } Add embed rule 

    = f.submit "Save", class: 'btn btn-success'

app/views/templates/edit_step2.haml
= render 'progress_bar', step: 2


#edit-template-form.form-wrapper.marg-bottom{ 'ng-controller' => 'EditTemplateFormCtrl', 'ng-init'=> "init(#{ @template.to_json(include: :embed_rules) })" }
  = simple_form_for @template, url: template_path(@template), html: { class: 'form-horizontal', name: 'TemplateForm' } do |f|

    #template-editor-window
      .image-wrapper{ 'ng-style' => "{ width: template.original_width + 200, height: template.original_height + 200 }" }
        .img-cover
        %canvas#img_canvas{ 'ng-style'=>"{'margin-left': current_rule.composite_position_x, 'margin-top': current_rule.composite_position_y}", height: "{{ current_rule.destination_size_y }}", width: "{{ current_rule.destination_size_x }}" }
        = image_tag @template.image_url

    .row.marg-bottom
      .col-md-12
        Original image size #{ @template.original_width }x#{ @template.original_height }

    .row.marg-bottom
      .col-md-12
        %button.btn.btn-xs.btn-primary{ 'eat-click' => true, 'ng-click' => 'add_embed_rule()' } Add embed rule

    .panel.panel-default.embed-rule{ 'ng-repeat' => 'rule in template.embed_rules', 'ng-class' => '{"panel-primary": current_rule == rule  }' }
      .panel-body
        %input{ type: :hidden, name: "template[embed_rules_attributes][][_destroy]", 'ng-model'=>"rule.deleted", value: "{{ rule.deleted }}" }
        .control-buttons.row-fluid

          .col-md-12
            %button.btn.btn-danger.btn-xs.pull-right{ 'ng-hide' => 'rule.deleted', 'eat-click' => true, 'ng-click' => 'remove_rule(rule)' } &times;
            %button.btn.btn-primary.btn-xs{ 'ng-hide' => 'rule.deleted || current_rule == rule', 'eat-click' => true, 'ng-click' => 'select_rule(rule)' } Select

        .alert.alert-danger{ 'ng-show'=>"rule.deleted" }
          Embed rule will be deleted (
          %a{ href: "#", 'ng-click'=>"rule.deleted=undefined", 'eat-click'=> true } Restore
          )

        .row{ 'ng-hide' => 'rule.deleted' }
          %input{ type: :hidden, name: 'image_template[embed_rules_attributes][][id]', value: '{{ rule.id }}' }
          .col-md-7
            .row.marg-bottom
              .col-md-3{ 'ng-repeat'=>'i in [0, 1, 2, 3]' }
                .point
                  .row
                    .col-md-12.text-center {{ point_names[i] }}
                  .row
                    %input.col-md-6{ value: "{{ get_init_distortion_points(rule, i*2) }}", readonly: true, disabled: true, type: :number,  placeholder: 'X' }
                    %input.col-md-6{ value: "{{ get_init_distortion_points(rule, i*2+1) }}", readonly: true, disabled: true, type: :number, placeholder: 'Y' }
                    
                    %input{ value: "{{ get_init_distortion_points(rule, i*2) }}", type: :hidden, name: "image_template[embed_rules_attributes][][destination_points][]" }
                    %input{ value: "{{ get_init_distortion_points(rule, i*2+1) }}", type: :hidden, name: "image_template[embed_rules_attributes][][destination_points][]" }
                  .row
                    %input.col-md-6{ 'ng-change'=>'redraw_canvas()', 'ng-model'=>'rule.destination_points[i*4+2]', value: '{{ rule.destination_points[i*4+2] }}', type: :number, name: "image_template[embed_rules_attributes][][destination_points][]", placeholder: 'X' }
                    %input.col-md-6{ 'ng-change'=>'redraw_canvas()', 'ng-model'=>'rule.destination_points[i*4+3]', value: '{{ rule.destination_points[i*4+3] }}', type: :number, name: "image_template[embed_rules_attributes][][destination_points][]", placeholder: 'Y' }
          .col-md-5
            .row.marg-bottom
              .col-md-6
                .row
                  .col-md-12 Composite position
                .row
                  .col-md-6
                    %label
                      X
                      %input.col-md-12{ name: 'image_template[embed_rules_attributes][][composite_position_x]', 'ng-change'=>'redraw_canvas()', 'ng-model'=>"rule.composite_position_x", type: :number }

                  
                  .col-md-6
                    %label
                      Y
                      %input.col-md-12{ name: 'image_template[embed_rules_attributes][][composite_position_y]', 'ng-change'=>'redraw_canvas()', 'ng-model'=>"rule.composite_position_y", type: :number }

              .col-md-6
                .row
                  .col-md-12 Destination size
                .row
                  .col-md-6
                    %label
                      Width
                      %input.col-md-12{ name: 'image_template[embed_rules_attributes][][destination_size_x]', 'ng-change'=>'redraw_canvas()', 'ng-model'=>"rule.destination_size_x", type: :number }
                 
                  .col-md-6
                    %label
                      Height
                      %input.col-md-12{ name: 'image_template[embed_rules_attributes][][destination_size_y]', 'ng-change'=>'redraw_canvas()', 'ng-model'=>"rule.destination_size_y", type: :number }
    
    .row
      .col-md-12
        %button.btn.btn-success.pull-right{ type: :submit, name: :commit, value: "move-to-step-3" } Save and move to next step >

app/views/templates/edit_step3.haml
= render 'progress_bar', step: 3


= simple_form_for @template, url: template_path(@template), html: { class: 'form-horizontal', name: 'TemplateForm' } do |f|
  .row.marg-bottom
    .col-xs-6
      = image_tag @template.image_url(:with_placeholder), class: "img-responsive"
    .col-xs-6
      = f.input :title, input_html: {class: "form-control"}
      = f.input :description, input_html: {class: "form-control"}
  
  .row.marg-bottom
    .col-md-12
      =link_to "< Back to step 2", edit_template_path(@template), class: "btn btn-success "
      %button.btn.btn-success.pull-right{ type: :submit, name: :commit, value: "template-complete" } Save

app/views/templates/index.html.haml
.page-header
  %h1 Templates

/ - @templates.in_groups_of(3, false) do |group|
/   .row
/     - group.each do |tpl|
/       .col-md-4
/         .template.panel.panel-default
/           .panel-body
/             = image_tag tpl.image_url(:small), class: 'img-responsive marg-bottom'
/             = link_to "Choose", template_path(tpl), class: 'btn btn-success btn-block'


.row
  .col-md-4
    - @col1_items.each do |tpl|
      = render 'template', tpl: tpl
  .col-md-4
    - @col2_items.each do |tpl|
      = render 'template', tpl: tpl
  .col-md-4
    - @col3_items.each do |tpl|
      = render 'template', tpl: tpl

app/views/templates/jcrop.html.haml
.page-header
  %h1 jcrop test

#show-template{ 'ng-controller' => 'CropTemplateCtrl', 'ng-init' => "image_url='#{ @template.image_url(:with_placeholder) }'; template_id='#{ params[:id] }'" }
  .row
    .col-md-8{ 'jrg-area-select'=> true }
      %img.img-responsive{ 'ng-src' => '{{ image_url }}', jcrop: '{{ jcropSettings }}', 'on-change-fn' => 'updateCoordinates(coords)' }
      %p hi there
      {{ coords }}
      %input{ value: "{{ coords.x }}" }
      %input{ value: "{{ coords.y }}" }
      %input{ value: "{{ coords.x2 }}" }
      %input{ value: "{{ coords.y2 }}" }
      %input{ value: "{{ coords.w }}" }
      %input{ value: "{{ coords.h }}" }

      %button{ 'ng-click' => 'updateCoordinates({g: 123})' } bbbbb

app/views/templates/new.html.haml
.page-header
  %h2 New Template Wizard

= render 'progress_bar', step: 1

.row
  .col-md-12
    = simple_form_for @template, url: templates_path, html: { class: 'form-vertical' } do |f|
      .form-group
        = f.input :image, label: false, input_html: { class: 'form-control2' }

      = f.submit "Upload", class: 'btn btn-default'

app/views/templates/show.html.haml
.page-header
  %h1= @template.title.present? ? @template.title : "Template"

#show-template{ 'ng-controller' => 'ShowTemplateCtrl', 'ng-init' => "init(#{ @template.to_json(include: [:embed_rules]) })" }
  .row
    .col-md-8
      .img-wrapper
        %img.img-responsive{ 'ng-src' => '{{ image_url }}' }
        .dropzone{ 'ng-repeat' => 'rule in template.embed_rules', 'ng-style' => 'positionForDropzone(rule)' }
          %label{ for: "file"}
            %input.file{ name: "processed_image[image]", 'ng-file-select'=>"onFileSelect($files, rule.id)",  type: "file" }
    
    //////////////////
    .col-md-4
      .control-group.error{ 'ng-cloak' => true }
        .progress.progress-striped.active{ 'ng-show' => 'is_uploading_photo' }
          .bar{ style: "width:{{ uploaded_percents }}%" }= t('.uploading')
        %span.help-inline{ 'ng-show' => 'photo_errors' } {{ photo_errors }}

      %h4 Description
      - if (description = @template.description).present?
        = description
      - else
        %p.text-muted Description is not specified

      %h4 Date
      %p.text-muted= l(@template.created_at, format: :short)

      - if true
        %ul.list-unstyled
          %li
            = link_to "Edit embedding area", edit_template_path(@template)
          %li
            = link_to "Edit Title & Description", edit_template_path(@template, step: "3")

  .row.marg-bottom
    %hr